package scouterclient;


//import com.spcrobotics.scouting.protocol.RspsAssignment;
import java.awt.Color;
import ScouterData.TeamMatchInfo;
import com.spcrobotics.scouting.protocol.*;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author david
 */

public class AutomaticGUI extends javax.swing.JFrame {
    
    public boolean done = false;
    
    public int tabNumber = 0;
    
   TeamMatchInfo teamMatchInfo = new TeamMatchInfo();
    /**
     * Creates new form Automatic
     */
    public AutomaticGUI() {
        initComponents();
		
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblMatchNumber = new javax.swing.JLabel();
        lblAlliance = new javax.swing.JLabel();
        lblTeamNumber = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        buttonCancel = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Match Number");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Alliance");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TeamNumber");

        lblMatchNumber.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblMatchNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMatchNumber.setText("jLabel4");

        lblAlliance.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblAlliance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlliance.setText("jLabel5");

        lblTeamNumber.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTeamNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTeamNumber.setText("jLabel6");

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        lblMessage.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMessage.setText("Assignment from Supervisor");

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblMatchNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAlliance, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(lblTeamNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(lblMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMatchNumber)
                            .addComponent(lblAlliance)
                            .addComponent(lblTeamNumber)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel1)))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        
        
        tabNumber = 1;
        this.setVisible(false);
        ScouterClient._sgui.setTitle();
        

    }//GEN-LAST:event_nextButtonActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonCancelActionPerformed
    {//GEN-HEADEREND:event_buttonCancelActionPerformed
        // TODO add your handling code here:
	this.setVisible(false);
                
    }//GEN-LAST:event_buttonCancelActionPerformed
	
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutomaticGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutomaticGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutomaticGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutomaticGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AutomaticGUI().setVisible(true);
            }
        });
        
    }
		public void Show(TeamMatchInfo t)
	{
		teamMatchInfo = t;
                
		this.setVisible(true);
		this.buttonCancel.setVisible(false);
		this.nextButton.setVisible(false);
		this.setLocationRelativeTo(null);
		if (teamMatchInfo.teamNumber == 0)
		{
			this.buttonCancel.setVisible(true);
			this.lblAlliance.setVisible(false);
			this.lblMatchNumber.setVisible(false);
			this.lblTeamNumber.setVisible(false);
			
			this.lblMessage.setText("All the matches have been given out.");
		} else
		{
            this.nextButton.setVisible(true);
			lblAlliance.setText(t.alliance);

			lblMatchNumber.setText("" + t.matchNumber);
			lblTeamNumber.setText("" + t.teamNumber);

			if (lblAlliance.getText() == "Blue")
			{
				lblTeamNumber.setForeground(Color.blue);
				lblMatchNumber.setForeground(Color.blue);
				lblAlliance.setForeground(Color.blue);
			} else if (lblAlliance.getText() == "Red")
			{
				lblTeamNumber.setForeground(Color.red);
				lblMatchNumber.setForeground(Color.red);
				lblAlliance.setForeground(Color.red);
				lblAlliance.setForeground(Color.red);
			}
		}
	}
//    public void show(RspsAssignment assignment, Record r){
//            this.lblAlliance.setText(String.valueOf(assignment.alliance));
//            this.lblTeamNumber.setText(String.valueOf(assignment.teamNumber));
//            this.lblMatchNumber.setText(String.valueOf(assignment.matchNumber));
//            record = r;
//            record.alliance = assignment.alliance.toString();
//            record.teamnum = assignment.teamNumber;
//            record.matchnum = assignment.matchNumber;
//            
//            this.setVisible(true);
//            this.setLocationRelativeTo(null);
//            
//            if(this.lblAlliance.getText() == "blue"){
//                lblAlliance.setForeground(Color.blue);
//            }
//            else if(this.lblAlliance.getText() == "red"){
//                lblAlliance.setForeground(Color.red);
//            }
//        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblAlliance;
    private javax.swing.JLabel lblMatchNumber;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblTeamNumber;
    private javax.swing.JButton nextButton;
    // End of variables declaration//GEN-END:variables
}
