/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scouterclient;
import ScouterData.Autonomous;
import ScouterData.Constants;
import ScouterData.TeamMatchInfo;
import ScouterData.Stack;

public class ScouterGUI extends javax.swing.JFrame {
    
    TeamMatchInfo teamMatchInfo = new TeamMatchInfo();
    ManualEnterGUI meGUI;
    AutomaticGUI aGUI;
    private static boolean isManual;
    static int stackCount = 0;
    public EndGUI endGUI;
    public ScouterGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
        public static Boolean getisManual()
	{
		return isManual;
	}
    
        public void setTitle()
	{
		this.setTitle(teamMatchInfo.scouterName + "Team : " + teamMatchInfo.teamNumber + ", Match : " + teamMatchInfo.matchNumber + ", Alliance : " + teamMatchInfo.alliance);
		System.out.println(teamMatchInfo.matchNumber + teamMatchInfo.teamNumber + teamMatchInfo.alliance);
	}
    
    	public void ScouterGUIShow(TeamMatchInfo t, int tabNum)
	{
                this.clear();
		this.setVisible(true);
		this.setLocationRelativeTo(null);
		teamMatchInfo = t;
		this.setTitle();
                ScouterClient._sgui.TabAuto.setSelectedIndex(tabNum);
	}
        
        public void ScouterGUINavigate(int tabNum)
	{

		this.setVisible(true);
		this.setLocationRelativeTo(null);
		this.setTitle();
                ScouterClient._sgui.TabAuto.setSelectedIndex(tabNum);
	}
        
        public void clear()
	{
            stackCount = 0;
            
            buttonGroup1.clearSelection();
            buttonGroup2.clearSelection();
            buttonGroup3.clearSelection();
            buttonGroup4.clearSelection();
            buttonGroup5.clearSelection();
            
            txtName.setText("");
            
            boolAuto.setSelected(false);
            boolMobilityAuto.setSelected(false);
            
            radioCan1.setSelected(false);
            radioCan2.setSelected(false);
            radioCan3.setSelected(false);
            radioCan4.setSelected(false);
            radioCan5.setSelected(false);
            
            radioTote1.setSelected(false);
            radioTote2.setSelected(false);
            radioTote3.setSelected(false);
            radioTote4.setSelected(false);
            radioTote5.setSelected(false);
            
            boolToteStack.setSelected(false);
            boolInterferedAuto.setSelected(false);
            txtInterferedAuto.setText("");
            
            boolCarryTote.setSelected(false);
            boolCarryCan.setSelected(false);
            boolStackTote.setSelected(false);
            boolStackCan.setSelected(false);
            boolMobilityEntire.setSelected(false);
            
            spnNoodleRec.setValue(0);
            spnNoodleUnRec.setValue(0);
            
            btn6High.setSelected(false);
            btn5High.setSelected(false);
            btn4High.setSelected(false);
            btn3High.setSelected(false);
            btn2High.setSelected(false);
            btn1High.setSelected(false);
            
            radioStackType1.setSelected(false);
            radioStackType2.setSelected(false);
            radioStackType3.setSelected(false);
            
            btnCoopAssist.setSelected(false);
            spnLevel1.setValue(0);
            spnLevel2.setValue(0);
            spnLevel3.setValue(0);
            spnLevel4.setValue(0);
            
            sldTote.setValue(0);
            sldCan.setValue(0);
            sldLitter.setValue(0);
            
            txtToteQ.setText("");
            txtCanQ.setText("");
            txtLitterQ.setText("");
            txtGeneralQ.setText("");
        }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        TabAuto = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnManual = new javax.swing.JButton();
        btnAutomatic = new javax.swing.JButton();
        picRenevatio = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        boolMobilityAuto = new javax.swing.JCheckBox();
        radioCan1 = new javax.swing.JRadioButton();
        radioCan2 = new javax.swing.JRadioButton();
        radioCan3 = new javax.swing.JRadioButton();
        radioCan4 = new javax.swing.JRadioButton();
        radioTote2 = new javax.swing.JRadioButton();
        radioTote1 = new javax.swing.JRadioButton();
        radioTote4 = new javax.swing.JRadioButton();
        radioTote5 = new javax.swing.JRadioButton();
        boolInterferedAuto = new javax.swing.JCheckBox();
        txtInterferedAuto = new javax.swing.JTextField();
        boolToteStack = new javax.swing.JCheckBox();
        boolAuto = new javax.swing.JCheckBox();
        radioCan5 = new javax.swing.JRadioButton();
        radioTote3 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        boolCarryTote = new javax.swing.JCheckBox();
        boolCarryCan = new javax.swing.JCheckBox();
        boolStackTote = new javax.swing.JCheckBox();
        boolStackCan = new javax.swing.JCheckBox();
        boolMobilityEntire = new javax.swing.JCheckBox();
        spnNoodleRec = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        btn6High = new javax.swing.JToggleButton();
        btn5High = new javax.swing.JToggleButton();
        btn4High = new javax.swing.JToggleButton();
        btn3High = new javax.swing.JToggleButton();
        btn2High = new javax.swing.JToggleButton();
        btn1High = new javax.swing.JToggleButton();
        radioStackType1 = new javax.swing.JRadioButton();
        radioStackType2 = new javax.swing.JRadioButton();
        radioStackType3 = new javax.swing.JRadioButton();
        btnTeleEnter = new javax.swing.JButton();
        spnNoodleUnRec = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnCoopAssist = new javax.swing.JCheckBox();
        spnLevel4 = new javax.swing.JSpinner();
        spnLevel1 = new javax.swing.JSpinner();
        spnLevel2 = new javax.swing.JSpinner();
        spnLevel3 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        sldTote = new javax.swing.JSlider();
        sldCan = new javax.swing.JSlider();
        sldLitter = new javax.swing.JSlider();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtToteQ = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCanQ = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtLitterQ = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtGeneralQ = new javax.swing.JTextArea();
        FinalSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabAuto.setMaximumSize(new java.awt.Dimension(350, 350));
        TabAuto.setMinimumSize(new java.awt.Dimension(350, 350));
        TabAuto.setPreferredSize(new java.awt.Dimension(350, 350));

        jPanel1.setMaximumSize(new java.awt.Dimension(350, 350));
        jPanel1.setPreferredSize(new java.awt.Dimension(350, 350));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Please Enter Your Name:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        btnManual.setText("Manual");
        btnManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManualActionPerformed(evt);
            }
        });

        btnAutomatic.setText("Automatic");
        btnAutomatic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutomaticActionPerformed(evt);
            }
        });

        picRenevatio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TeamLogo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtName))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnManual, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAutomatic, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(picRenevatio)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAutomatic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addComponent(picRenevatio)
                .addGap(115, 115, 115))
        );

        TabAuto.addTab("Start", jPanel1);

        jPanel2.setMaximumSize(new java.awt.Dimension(350, 450));
        jPanel2.setMinimumSize(new java.awt.Dimension(350, 400));
        jPanel2.setPreferredSize(new java.awt.Dimension(350, 400));

        boolMobilityAuto.setText("Mobility");
        boolMobilityAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boolMobilityAutoActionPerformed(evt);
            }
        });

        buttonGroup2.add(radioCan1);
        radioCan1.setText("No attempt to pick up can");
        radioCan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCan1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(radioCan2);
        radioCan2.setText("Attempt to pick up can");

        buttonGroup2.add(radioCan3);
        radioCan3.setText("Moved 1 bin");

        buttonGroup2.add(radioCan4);
        radioCan4.setText("Moved 2 bins");
        radioCan4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCan4ActionPerformed(evt);
            }
        });

        buttonGroup3.add(radioTote2);
        radioTote2.setText("Attempt to pick up tote");

        buttonGroup3.add(radioTote1);
        radioTote1.setText("No attempt to pick up tote");
        radioTote1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTote1ActionPerformed(evt);
            }
        });

        buttonGroup3.add(radioTote4);
        radioTote4.setText("Picked up tote");

        buttonGroup3.add(radioTote5);
        radioTote5.setText("Picked up and moved tote to auto zone  ");
        radioTote5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTote5ActionPerformed(evt);
            }
        });

        boolInterferedAuto.setText("Interfered with other robots autonomous (Comment)");
        boolInterferedAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boolInterferedAutoActionPerformed(evt);
            }
        });

        boolToteStack.setText("Stacked Totes");

        boolAuto.setText("Made It to Auto Zone");

        buttonGroup2.add(radioCan5);
        radioCan5.setText("Moved 3 bins");

        buttonGroup3.add(radioTote3);
        radioTote3.setText("Moved 1 tote");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioTote3)
                    .addComponent(radioCan5)
                    .addComponent(boolAuto)
                    .addComponent(boolToteStack)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(boolMobilityAuto)
                        .addComponent(radioCan1)
                        .addComponent(radioCan2)
                        .addComponent(radioCan3)
                        .addComponent(radioCan4)
                        .addComponent(radioTote2)
                        .addComponent(radioTote1)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(radioTote4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(186, 186, 186))
                        .addComponent(radioTote5)
                        .addComponent(boolInterferedAuto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(txtInterferedAuto))))
                .addGap(156, 156, 156))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boolMobilityAuto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boolAuto)
                .addGap(18, 18, 18)
                .addComponent(radioCan1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioCan2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioCan3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioCan4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioCan5)
                .addGap(18, 18, 18)
                .addComponent(radioTote1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioTote2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioTote3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioTote4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioTote5)
                .addGap(33, 33, 33)
                .addComponent(boolToteStack)
                .addGap(46, 46, 46)
                .addComponent(boolInterferedAuto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtInterferedAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        TabAuto.addTab("Autonomous", jPanel2);

        jPanel3.setMaximumSize(new java.awt.Dimension(500, 500));
        jPanel3.setMinimumSize(new java.awt.Dimension(500, 500));

        boolCarryTote.setText("Carry Tote");

        boolCarryCan.setText("Carry Can");

        boolStackTote.setText("Stack Tote");

        boolStackCan.setText("Stack Can");

        boolMobilityEntire.setText("Mobility For Entire Round");

        jLabel2.setText("Recycled Litter");

        btn6High.setText("6 High");

        btn5High.setText("5 High");

        btn4High.setText("4 High");
        btn4High.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4HighActionPerformed(evt);
            }
        });

        btn3High.setText("3 High");

        btn2High.setText("2 High");

        btn1High.setText("1 High");

        buttonGroup5.add(radioStackType1);
        radioStackType1.setText("Tote");

        buttonGroup5.add(radioStackType2);
        radioStackType2.setText("Can");

        buttonGroup5.add(radioStackType3);
        radioStackType3.setText("Can With Noodle");

        btnTeleEnter.setText("Enter");
        btnTeleEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeleEnterActionPerformed(evt);
            }
        });

        jLabel15.setText("Unrecycled Litter");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(radioStackType3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTeleEnter))
                    .addComponent(radioStackType2)
                    .addComponent(radioStackType1)
                    .addComponent(boolCarryTote)
                    .addComponent(boolCarryCan)
                    .addComponent(boolStackTote)
                    .addComponent(boolStackCan)
                    .addComponent(boolMobilityEntire)
                    .addComponent(btn3High)
                    .addComponent(btn5High)
                    .addComponent(btn6High)
                    .addComponent(btn4High)
                    .addComponent(btn2High)
                    .addComponent(btn1High)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(spnNoodleUnRec, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnNoodleRec, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel15))))
                .addContainerGap(324, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boolCarryTote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boolCarryCan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boolStackTote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boolStackCan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boolMobilityEntire)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnNoodleRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnNoodleUnRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(32, 32, 32)
                .addComponent(btn6High)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn5High)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn4High)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn3High)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn2High)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn1High)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioStackType1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioStackType2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioStackType3)
                    .addComponent(btnTeleEnter))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        TabAuto.addTab("Teleoperated", jPanel3);

        jPanel4.setMaximumSize(new java.awt.Dimension(500, 500));
        jPanel4.setMinimumSize(new java.awt.Dimension(500, 500));

        btnCoopAssist.setText("Assist");
        btnCoopAssist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoopAssistActionPerformed(evt);
            }
        });

        jLabel3.setText("Level 1");

        jLabel5.setText("Level 2");

        jLabel6.setText("Level 3");

        jLabel7.setText("Level 4");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCoopAssist)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(spnLevel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(spnLevel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnLevel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnLevel4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))))
                .addContainerGap(412, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCoopAssist)
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnLevel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnLevel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnLevel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnLevel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(372, Short.MAX_VALUE))
        );

        TabAuto.addTab("Coopertition", jPanel4);

        jPanel5.setMaximumSize(new java.awt.Dimension(500, 500));
        jPanel5.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel5.setPreferredSize(new java.awt.Dimension(500, 500));

        sldTote.setMajorTickSpacing(1);
        sldTote.setMaximum(5);
        sldTote.setPaintLabels(true);
        sldTote.setPaintTicks(true);
        sldTote.setSnapToTicks(true);
        sldTote.setToolTipText("");
        sldTote.setValue(0);
        sldTote.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        sldCan.setMajorTickSpacing(1);
        sldCan.setMaximum(5);
        sldCan.setPaintLabels(true);
        sldCan.setPaintTicks(true);
        sldCan.setSnapToTicks(true);
        sldCan.setValue(0);

        sldLitter.setMajorTickSpacing(1);
        sldLitter.setMaximum(5);
        sldLitter.setPaintLabels(true);
        sldLitter.setPaintTicks(true);
        sldLitter.setSnapToTicks(true);
        sldLitter.setValue(0);

        jLabel8.setText("Tote Ranking");

        jLabel9.setText("Can Ranking");

        jLabel10.setText("Litter Ranking");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Comments:");

        txtToteQ.setColumns(20);
        txtToteQ.setLineWrap(true);
        txtToteQ.setRows(5);
        jScrollPane2.setViewportView(txtToteQ);

        jLabel4.setText("Where did they get their totes from and how? ");

        jLabel12.setText("Where did they get their cylinders from and how? ");

        txtCanQ.setColumns(20);
        txtCanQ.setLineWrap(true);
        txtCanQ.setRows(5);
        jScrollPane1.setViewportView(txtCanQ);

        jLabel13.setText("How did they recycle litter?");

        txtLitterQ.setColumns(20);
        txtLitterQ.setLineWrap(true);
        txtLitterQ.setRows(5);
        jScrollPane3.setViewportView(txtLitterQ);

        jLabel14.setText("General Questiions:");

        txtGeneralQ.setColumns(20);
        txtGeneralQ.setRows(5);
        jScrollPane4.setViewportView(txtGeneralQ);

        FinalSubmit.setText("Submit");
        FinalSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(sldTote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(sldCan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(sldLitter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addComponent(jLabel11)
                    .addComponent(jLabel4)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane3)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FinalSubmit)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(FinalSubmit))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sldTote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sldCan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sldLitter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4)))
                .addContainerGap())
        );

        TabAuto.addTab("Summary", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabAuto, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabAuto, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        TabAuto.getAccessibleContext().setAccessibleName("StartTab");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
       
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManualActionPerformed
        meGUI = new ManualEnterGUI();
        meGUI.setVisible(true);
        teamMatchInfo = meGUI.teamMatchInfo;
        teamMatchInfo.scouterName = txtName.getText();
        this.ScouterGUINavigate(1);
    }//GEN-LAST:event_btnManualActionPerformed

    private void boolMobilityAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boolMobilityAutoActionPerformed

    }//GEN-LAST:event_boolMobilityAutoActionPerformed

    private void radioCan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioCan1ActionPerformed

    private void radioCan4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCan4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioCan4ActionPerformed

    private void radioTote1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTote1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioTote1ActionPerformed

    private void boolInterferedAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boolInterferedAutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boolInterferedAutoActionPerformed

    private void btn4HighActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4HighActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4HighActionPerformed

    private void FinalSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalSubmitActionPerformed
        
        teamMatchInfo.autonomous.mobility = boolMobilityAuto.isSelected();
       
       teamMatchInfo.autonomous.mobility = boolAuto.isSelected();
       
       if (radioCan1.isSelected()){
           teamMatchInfo.autonomous.binState = 1;
       }
       else if (radioCan2.isSelected()){
           teamMatchInfo.autonomous.binState = 2;
       }
       else if (radioCan3.isSelected()){
           teamMatchInfo.autonomous.binState = 3;
       }
       else if (radioCan4.isSelected()){
           teamMatchInfo.autonomous.binState = 4;
       }
       else if (radioCan5.isSelected()){
           teamMatchInfo.autonomous.binState = 5;
       }
       else{
           teamMatchInfo.autonomous.binState = 0;
       }
       
        if (radioTote1.isSelected()){
           teamMatchInfo.autonomous.toteState = 1;
       }
       else if (radioTote2.isSelected()){
           teamMatchInfo.autonomous.toteState = 2;
       }
       else if (radioTote3.isSelected()){
           teamMatchInfo.autonomous.toteState = 3;
       }
       else if (radioTote4.isSelected()){
           teamMatchInfo.autonomous.toteState = 4;
       }
       else if (radioTote5.isSelected()){
           teamMatchInfo.autonomous.toteState = 5;
       }
       else{
           teamMatchInfo.autonomous.toteState = 0;
       }
        
        teamMatchInfo.autonomous.toteStack = boolToteStack.isSelected();
        
        teamMatchInfo.autonomous.interferedAuto = boolInterferedAuto.isSelected();
        
        teamMatchInfo.autonomous.comment = txtInterferedAuto.getText();
        

        
        teamMatchInfo.toteCarry = boolCarryTote.isSelected();
        teamMatchInfo.binCarry = boolCarryCan.isSelected();
        teamMatchInfo.toteStack = boolStackTote.isSelected();
        teamMatchInfo.binStack = boolStackCan.isSelected(); 
        teamMatchInfo.mobility = boolMobilityEntire.isSelected();
        teamMatchInfo.recycledLitter = (int) spnNoodleRec.getValue();
        teamMatchInfo.unrecycledLitter = (int) spnNoodleUnRec.getValue();
        
        teamMatchInfo.toteRank = sldTote.getValue();
        teamMatchInfo.binRank = sldCan.getValue();
        teamMatchInfo.litterRank = sldLitter.getValue();
        
        teamMatchInfo.toteComment = txtCanQ.getText();
        teamMatchInfo.litterComment = txtLitterQ.getText();
        teamMatchInfo.binComment = txtCanQ.getText();
        teamMatchInfo.comment = txtGeneralQ.getText();
        
        teamMatchInfo.coopAssist = btnCoopAssist.isSelected();
        teamMatchInfo.coop[0] = (Integer) spnLevel1.getValue();
        teamMatchInfo.coop[1] = (Integer) spnLevel2.getValue();
        teamMatchInfo.coop[2] = (Integer) spnLevel3.getValue();
        teamMatchInfo.coop[3] = (Integer) spnLevel4.getValue();
        
        teamMatchInfo.toteCarry = boolCarryTote.isSelected();
        teamMatchInfo.binCarry = boolCarryCan.isSelected();
        teamMatchInfo.toteStack = boolStackTote.isSelected();
        teamMatchInfo.binStack = boolStackCan.isSelected(); 
        teamMatchInfo.mobility = boolMobilityEntire.isSelected();
        teamMatchInfo.recycledLitter = (int) spnNoodleRec.getValue();
        teamMatchInfo.unrecycledLitter = (int) spnNoodleUnRec.getValue();
                 
        
        endGUI = new EndGUI(teamMatchInfo);
        endGUI.setVisible(true);
        
        if(endGUI.tabNumber == 0)
        {
            teamMatchInfo = new TeamMatchInfo();
            this.ScouterGUIShow(teamMatchInfo, endGUI.tabNumber);
        }
        else
        {
            this.ScouterGUINavigate(endGUI.tabNumber);
        }
        
        
    }//GEN-LAST:event_FinalSubmitActionPerformed

    private void radioTote5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTote5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioTote5ActionPerformed

    private void btnAutomaticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutomaticActionPerformed
        aGUI = new AutomaticGUI();
        aGUI.setVisible(true);
        if(aGUI.tabNumber == 1)
        {
            teamMatchInfo = aGUI.teamMatchInfo;
            teamMatchInfo.scouterName = txtName.getText();
            this.ScouterGUINavigate(aGUI.tabNumber);
        }
        else
        {
            this.ScouterGUINavigate(aGUI.tabNumber);
        }
        
    }//GEN-LAST:event_btnAutomaticActionPerformed

    private void btnTeleEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeleEnterActionPerformed
        Stack tempStack = new Stack(stackCount);
        for(int i = 0; i < 6; i++)
        {
            tempStack.stack[i] = Constants.StackObjects.Nothing;
        }
        stackCount++;
        
        boolean binCreated = false;
        if(radioStackType3.isSelected())
        {
            if(btn6High.isSelected())
            {
                tempStack.stack[5] = Constants.StackObjects.BinWithLitter;
                binCreated = true;
            }
            if(btn5High.isSelected() && binCreated == true)
            {
                tempStack.stack[4] = Constants.StackObjects.Tote;
            }
            else if(btn5High.isSelected() && binCreated == false)
            {
                tempStack.stack[4] = Constants.StackObjects.BinWithLitter;
                binCreated = true;
            }
            if(btn4High.isSelected() && binCreated == true)
            {
                tempStack.stack[3] = Constants.StackObjects.Tote;
            }
            else if(btn4High.isSelected() && binCreated == false)
            {
                tempStack.stack[3] = Constants.StackObjects.BinWithLitter;
                binCreated = true;
            }
            if(btn3High.isSelected() && binCreated == true)
            {
                tempStack.stack[2] = Constants.StackObjects.Tote;
            }
            else if(btn3High.isSelected() && binCreated == false)
            {
                tempStack.stack[2] = Constants.StackObjects.BinWithLitter;
                binCreated = true;
            }
            if(btn2High.isSelected() && binCreated == true)
            {
                tempStack.stack[1] = Constants.StackObjects.Tote;
            }
            else if(btn2High.isSelected() && binCreated == false)
            {
                tempStack.stack[1] = Constants.StackObjects.BinWithLitter;
                binCreated = true;
            }
            if(btn1High.isSelected() && binCreated == true)
            {
                tempStack.stack[0] = Constants.StackObjects.Tote;
            }
            else if(btn1High.isSelected() && binCreated == false)
            {
                tempStack.stack[0] = Constants.StackObjects.BinWithLitter;
                binCreated = true;
            }
            
        }
        else if(radioStackType2.isSelected())
        {
            if(btn6High.isSelected())
            {
                tempStack.stack[5] = Constants.StackObjects.BinWithoutLitter;
                binCreated = true;
            }
            if(btn5High.isSelected() && binCreated == true)
            {
                tempStack.stack[4] = Constants.StackObjects.Tote;
            }
            else if(btn5High.isSelected() && binCreated == false)
            {
                tempStack.stack[4] = Constants.StackObjects.BinWithoutLitter;
                binCreated = true;
            }
            if(btn4High.isSelected() && binCreated == true)
            {
                tempStack.stack[3] = Constants.StackObjects.Tote;
            }
            else if(btn4High.isSelected() && binCreated == false)
            {
                tempStack.stack[3] = Constants.StackObjects.BinWithoutLitter;
                binCreated = true;
            }
            if(btn3High.isSelected() && binCreated == true)
            {
                tempStack.stack[2] = Constants.StackObjects.Tote;
            }
            else if(btn3High.isSelected() && binCreated == false)
            {
                tempStack.stack[2] = Constants.StackObjects.BinWithoutLitter;
                binCreated = true;
            }
            if(btn2High.isSelected() && binCreated == true)
            {
                tempStack.stack[1] = Constants.StackObjects.Tote;
            }
            else if(btn2High.isSelected() && binCreated == false)
            {
                tempStack.stack[1] = Constants.StackObjects.BinWithoutLitter;
                binCreated = true;
            }
            if(btn1High.isSelected() && binCreated == true)
            {
                tempStack.stack[0] = Constants.StackObjects.Tote;
            }
            else if(btn1High.isSelected() && binCreated == false)
            {
                tempStack.stack[0] = Constants.StackObjects.BinWithoutLitter;
                binCreated = true;
            }
        }
        else
        {
            if(btn6High.isSelected())
            {
                tempStack.stack[5] = Constants.StackObjects.Tote;
            }
            if(btn5High.isSelected())
            {
                tempStack.stack[4] = Constants.StackObjects.Tote;
            }
            if(btn4High.isSelected())
            {
                tempStack.stack[3] = Constants.StackObjects.Tote;
            }
            if(btn3High.isSelected())
            {
                tempStack.stack[2] = Constants.StackObjects.Tote;
            }
            if(btn2High.isSelected())
            {
                tempStack.stack[1] = Constants.StackObjects.Tote;
            }
            if(btn1High.isSelected())
            {
                tempStack.stack[0] = Constants.StackObjects.Tote;
            }
        }
        teamMatchInfo.stacks.add(tempStack);
        buttonGroup5.clearSelection();
        
        btn6High.setSelected(false);
        btn5High.setSelected(false);
        btn4High.setSelected(false);
        btn3High.setSelected(false);
        btn2High.setSelected(false);
        btn1High.setSelected(false);
        
    }//GEN-LAST:event_btnTeleEnterActionPerformed

    private void btnCoopAssistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoopAssistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCoopAssistActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScouterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScouterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScouterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScouterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScouterGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FinalSubmit;
    public javax.swing.JTabbedPane TabAuto;
    private javax.swing.JCheckBox boolAuto;
    private javax.swing.JCheckBox boolCarryCan;
    private javax.swing.JCheckBox boolCarryTote;
    private javax.swing.JCheckBox boolInterferedAuto;
    private javax.swing.JCheckBox boolMobilityAuto;
    private javax.swing.JCheckBox boolMobilityEntire;
    private javax.swing.JCheckBox boolStackCan;
    private javax.swing.JCheckBox boolStackTote;
    private javax.swing.JCheckBox boolToteStack;
    private javax.swing.JToggleButton btn1High;
    private javax.swing.JToggleButton btn2High;
    private javax.swing.JToggleButton btn3High;
    private javax.swing.JToggleButton btn4High;
    private javax.swing.JToggleButton btn5High;
    private javax.swing.JToggleButton btn6High;
    private javax.swing.JButton btnAutomatic;
    private javax.swing.JCheckBox btnCoopAssist;
    private javax.swing.JButton btnManual;
    private javax.swing.JButton btnTeleEnter;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel picRenevatio;
    private javax.swing.JRadioButton radioCan1;
    private javax.swing.JRadioButton radioCan2;
    private javax.swing.JRadioButton radioCan3;
    private javax.swing.JRadioButton radioCan4;
    private javax.swing.JRadioButton radioCan5;
    private javax.swing.JRadioButton radioStackType1;
    private javax.swing.JRadioButton radioStackType2;
    private javax.swing.JRadioButton radioStackType3;
    private javax.swing.JRadioButton radioTote1;
    private javax.swing.JRadioButton radioTote2;
    private javax.swing.JRadioButton radioTote3;
    private javax.swing.JRadioButton radioTote4;
    private javax.swing.JRadioButton radioTote5;
    private javax.swing.JSlider sldCan;
    private javax.swing.JSlider sldLitter;
    private javax.swing.JSlider sldTote;
    private javax.swing.JSpinner spnLevel1;
    private javax.swing.JSpinner spnLevel2;
    private javax.swing.JSpinner spnLevel3;
    private javax.swing.JSpinner spnLevel4;
    private javax.swing.JSpinner spnNoodleRec;
    private javax.swing.JSpinner spnNoodleUnRec;
    private javax.swing.JTextArea txtCanQ;
    private javax.swing.JTextArea txtGeneralQ;
    private javax.swing.JTextField txtInterferedAuto;
    private javax.swing.JTextArea txtLitterQ;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextArea txtToteQ;
    // End of variables declaration//GEN-END:variables
}
